# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userIdx', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('loginToken', models.TextField(blank=True, default='')),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
