# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0003_auto_20160730_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
