# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0004_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
