# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0005_auto_20160731_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
