# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0006_auto_20160731_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('friend_idx', models.AutoField(primary_key=True, serialize=False)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='friends',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_receiver', to='shnam_app.User'),
        ),
        migrations.AddField(
            model_name='friends',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_sender', to='shnam_app.User'),
        ),
    ]
