# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0008_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_receiver_id', to='shnam_app.User'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_sender_id', to='shnam_app.User'),
        ),
    ]
