# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0009_auto_20160731_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
