# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0010_friends_disable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([('sender_id', 'receiver_id')]),
        ),
    ]
