# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0013_auto_20160731_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='sender_id',
        ),
        migrations.AddField(
            model_name='friends',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shnam_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shnam_app.User'),
            preserve_default=False,
        ),
    ]
