# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0016_auto_20160731_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friends',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='friends',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='sender',
        ),
    ]
