# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0018_auto_20160731_1852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='friends',
            new_name='Friend',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([]),
        ),
    ]
