# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0020_auto_20160731_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
    ]
