# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0036_auto_20160801_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shnam_app.User', to_field='email'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shnam_app.User', to_field='email'),
        ),
    ]
