# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0038_auto_20160801_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicMsg',
            fields=[
                ('msgIdx', models.AutoField(primary_key=True, serialize=False)),
                ('uri', models.CharField(blank=True, max_length=100, null=True)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_receiver', to='shnam_app.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_sender', to='shnam_app.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='musicmsg',
            unique_together=set([('sender', 'receiver')]),
        ),
    ]
