# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0042_auto_20160802_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='receiverid',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='senderid',
            new_name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('sender', 'receiver')]),
        ),
    ]
