# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0046_auto_20160802_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmsg',
            name='music_receiver',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='music_receiver', to='shnam_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicmsg',
            name='music_sender',
            field=models.ForeignKey(default=29, on_delete=django.db.models.deletion.CASCADE, related_name='music_sender', to='shnam_app.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='musicmsg',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='musicmsg',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='musicmsg',
            unique_together=set([('music_sender', 'music_receiver')]),
        ),
    ]
