# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0047_auto_20160802_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musicmsg',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='musicmsg',
            name='music_receiver',
        ),
        migrations.RemoveField(
            model_name='musicmsg',
            name='music_sender',
        ),
    ]
