# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0052_auto_20160802_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicmsg',
            name='followObj',
        ),
        migrations.AddField(
            model_name='musicmsg',
            name='receiver',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='shnam_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicmsg',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='shnam_app.User'),
            preserve_default=False,
        ),
    ]
