# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-02 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0053_auto_20160802_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicmsg',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='musicmsg',
            name='sender',
        ),
    ]
