# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0055_musicmsg_followobj'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('ErrorId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(default='')),
                ('callFunc', models.TextField(blank=True, default='')),
                ('status', models.TextField(blank=True, default='')),
                ('responseText', models.TextField(blank=True, default='')),
                ('errmsg', models.TextField(blank=True, default='')),
                ('createdTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
