# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0056_auto_20160815_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
