# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shnam_app', '0057_auto_20160815_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
